# Generated by Django 5.1.1 on 2024-09-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_anuncio_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='data_criacao',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='galeria.categoria'),
        ),
    ]
